language: python
python:
    - "2.7"

env:
  global:
    - SECRET_KEY_RAZ="test§$%§$§%"
    - DJANGO_SETTINGS_MODULE="ionescu77Project.settings.razvansky"

# command to install dependencies
install:
    - pip install -r requirements/test.txt

# command to run tests
script:
    nosetests
after_success:
    coveralls

