language: python

python:
    - "2.7"

services:
    - postgresql

env:
  global:
    - SECRET_KEY_RAZ="test§$%§$§%"
    - DJANGO_SETTINGS_MODULE="ionescu77Project.settings.staging"

# command to install dependencies
install:
    - pip install -r requirements/test.txt

before_script:
    - psql -c "CREATE DATABASE travisci;" -U postgres
    - cd src; python manage.py syncdb --noinput

# command to run tests
script:
    nosetests

after_success:
    coveralls
